export const students = [
  {
    id: "1",
    fullName: "Ahmed Alaa",
    age: "16",
    email: "ahmed@gmail.com",
    enrolledClass: "React",
  },
  {
    id: "2",
    fullName: "Sara Mohamed",
    age: "17",
    email: "sara@gmail.com",
    enrolledClass: "React",
  },
  {
    id: "3",
    fullName: "Omar Hassan",
    age: "18",
    email: "omar@gmail.com",
    enrolledClass: "React",
  },
  {
    id: "4",
    fullName: "Laila Youssef",
    age: "19",
    email: "laila@gmail.com",
    enrolledClass: "React",
  },
  {
    id: "5",
    fullName: "Mohamed Tarek",
    age: "20",
    email: "mohamed@gmail.com",
    enrolledClass: "React",
  },
  {
    id: "6",
    fullName: "Mona Adel",
    age: "21",
    email: "mona@gmail.com",
    enrolledClass: "React",
  },
  {
    id: "7",
    fullName: "Khaled Nabil",
    age: "22",
    email: "khaled@gmail.com",
    enrolledClass: "React",
  },
  {
    id: "8",
    fullName: "Nour Samir",
    age: "23",
    email: "nour@gmail.com",
    enrolledClass: "React",
  },
  {
    id: "9",
    fullName: "Yasmine Farid",
    age: "24",
    email: "yasmine@gmail.com",
    enrolledClass: "React",
  },
  {
    id: "10",
    fullName: "Tamer Saeed",
    age: "25",
    email: "tamer@gmail.com",
    enrolledClass: "React",
  },
];
